import json, os, hashlib
def get_file_hash(filepath):
    h = hashlib.sha256()
    try:
        with open(filepath, 'rb') as f:
            while chunk := f.read(8192):
                h.update(chunk)
        return h.hexdigest()
    except Exception:
        return "hash_error"

# Just pasting the 9 json strings generated by the agents directly.
responses = [
    # icon 175
    ("/Users/markoates/Assets/kazzter-k/interface-icons/extracted/User Interface Icons/Separated Icons/300% Icons/icon_175.png", '''{"catalog_proposal": {"type": "sprite_sheet_cell", "perspective": "ui_overlay", "num_frames": 1, "cell_dimensions": {"width": 24, "height": 24}, "is_subframe": false, "is_icon": true, "inferred_grid": null}, "theme_profile": {"description": "A diagonal metallic bar or ingot UI icon with silver and white highlights.", "tags": ["icon", "metal", "ingot", "bar", "item", "material", "300%"], "style": "pixel art", "color_descriptors": ["silver", "white", "dark gray"]}, "inference_reasoning": [{"rule": "Rule 7: UI & HUD", "rationale": "File is located within the User Interface Icons directory structure."}, {"rule": "Rule 12: Icons & Small Graphics", "rationale": "Asset is a small standalone graphic representing an item or material, flagged as an icon."}, {"rule": "Rule 16: Perspective Analysis", "rationale": "Iconography rendered flat for user interface usage, categorized as ui_overlay perspective."}]}'''),
    
    # explosion 0007
    ("/Users/markoates/Assets/untiedgames/super-pixel-effects-pack-1/extracted/Super Pixel Effects Pack 1/PNG/fx1_explosion_small_violet/frame0007.png", '''{"catalog_proposal": {"type": "multi_file_animation", "perspective": "side", "num_frames": 1, "cell_dimensions": {"width": null, "height": null}, "is_subframe": true, "is_icon": false, "inferred_grid": null}, "theme_profile": {"description": "Frame 7 of a small violet pixel art explosion visual effect animation.", "tags": ["explosion", "vfx", "violet", "pixel_art", "animation_frame", "particles"], "style": "Retro Pixel Art", "color_descriptors": ["violet", "white", "light blue", "purple"]}, "inference_reasoning": [{"rule": "Rule 4: Multi-File Sequences", "rationale": "Filename ends in sequential numbering (frame0007.png), denoting a multi_file_animation with is_subframe set to true."}, {"rule": "Rule 8: Visual Effects (VFX)", "rationale": "Keywords fx1_ and explosion in the directory path indicate a particle/VFX asset."}, {"rule": "Rule 16: Perspective Analysis", "rationale": "Effect is rendered from a side perspective typical of 2D side-scrolling platformers."}]}'''),

    # helmet 168
    ("/Users/markoates/Assets/pixeltier/pixeltiers-16x16-rpg-icon-pack/extracted/Pixeltiers_16x16_RPG_Pack_Update_8/helmets/helmet_168.png", '''{"catalog_proposal": {"type": "sprite_sheet_cell", "perspective": "ui_overlay", "num_frames": 1, "cell_dimensions": {"width": 16, "height": 16}, "is_subframe": false, "is_icon": true, "inferred_grid": null}, "theme_profile": {"description": "A detailed pixel art helmet equipment icon with gold ornamentation on dark armor plate.", "tags": ["helmet", "armor", "equipment", "rpg", "pixel_art", "headgear"], "style": "16x16 pixel art RPG icon", "color_descriptors": ["dark blue", "gold", "orange", "white"]}, "inference_reasoning": [{"rule": "Rule 2: Embedded Resolution", "rationale": "Filename and path indicate 16x16px RPG icon pack asset."}, {"rule": "Rule 12: Icons & Small Graphics", "rationale": "The asset is a 16x16 standalone graphic representing an item/equipment piece (helmet), so is_icon is true."}, {"rule": "Rule 16: Perspective Analysis", "rationale": "Inventory item icons are viewed as UI overlay elements."}]}'''),

    # shirt 18
    ("/Users/markoates/Assets/pixeltier/pixeltiers-16x16-rpg-icon-pack/extracted/Pixeltiers_16x16_RPG_Pack_Update_8/shirts/shirt_18.png", '''{"catalog_proposal": {"type": "sprite_sheet_cell", "perspective": "ui_overlay", "num_frames": 1, "cell_dimensions": {"width": 16, "height": 16}, "is_subframe": false, "is_icon": true, "inferred_grid": null}, "theme_profile": {"description": "A 16x16 pixel art icon of a white collared shirt for RPG character equipment.", "tags": ["shirt", "clothing", "equipment", "item", "rpg", "pixel_art"], "style": "Retro pixel art", "color_descriptors": ["white", "cream", "dark navy"]}, "inference_reasoning": [{"rule": "Rule 2: Embedded Resolution", "rationale": "The file path indicates a 16x16px RPG icon pack, setting the cell dimensions to 16x16."}, {"rule": "Rule 12: Icons & Small Graphics", "rationale": "The asset is a 16x16 standalone graphic representing an inventory clothing item, so is_icon is set to true."}, {"rule": "Rule 16: Perspective Analysis", "rationale": "Inventory and equipment items are displayed as flat UI icons, categorized as ui_overlay perspective."}]}'''),

    # mockup
    ("/Users/markoates/Assets/rafaelmatos/epic-rpg-world-asset-pack-crypt/extracted/EPIC RPG World Pack - Crypt V.1.5.1/Mockups/mockup1-2-close.gif", '''{"catalog_proposal": {"type": "preview", "perspective": "side", "num_frames": 1, "cell_dimensions": {"width": null, "height": null}, "is_subframe": false, "is_icon": false, "inferred_grid": null}, "theme_profile": {"description": "A detailed pixel art environment mockup of a dark crypt dungeon featuring stone architecture, staircases, torches, red banners, and scattered skeletal remains and pottery.", "tags": ["mockup", "crypt", "dungeon", "preview", "environment", "pixel_art", "staircase", "torches"], "style": "Dark gothic pixel art", "color_descriptors": ["dark teal", "slate blue", "amber", "crimson red"]}, "inference_reasoning": [{"rule": "Rule 9: Mockups & Previews", "rationale": "Filename contains 'mockup' (mockup1-2-close.gif), identifying it as a valid preview asset."}, {"rule": "Rule 16: Perspective Analysis", "rationale": "The scene displays a 2D side-scrolling platformer / adventure perspective of a dungeon interior with vertical walls, arches, and descending stairs."}]}'''),

    # lightning
    ("/Users/markoates/Assets/rafaelmatos/epic-rpg-world-the-depths-of-the-mountain/extracted/Epic RPG World - The dephs of the Mountain V1.2/Props/Animated props/individual files/lightning-1tile-frame12.png", '''{"catalog_proposal": {"type": "multi_file_animation", "perspective": "side", "num_frames": 1, "cell_dimensions": {"width": null, "height": null}, "is_subframe": true, "is_icon": false, "inferred_grid": null}, "theme_profile": {"description": "A single frame of a glowing blue lightning bolt animation effect, designed for atmospheric environmental props.", "tags": ["lightning", "electricity", "prop", "animation", "vfx", "cave", "magic"], "style": "Pixel Art", "color_descriptors": ["electric blue", "white", "cyan"]}, "inference_reasoning": [{"rule": "Rule 4: Multi-File Sequences", "rationale": "Filename ends with sequential frame numbering (-frame12), designating it as part of a multi-file animation sequence with is_subframe set to true."}, {"rule": "Rule 8: Visual Effects (VFX)", "rationale": "Keywords like lightning denote particle/VFX asset."}, {"rule": "Rule 16: Perspective Analysis", "rationale": "Environmental props in this pack are structured for side-scroller/platformer views."}]}'''),

    # shield 14
    ("/Users/markoates/Assets/untiedgames/super-pixel-effects-pack-1/extracted/Super Pixel Effects Pack 1/PNG/fx1_energy_shield_large_black/frame0014.png", '''{"catalog_proposal": {"type": "multi_file_animation", "perspective": "side", "num_frames": 1, "cell_dimensions": {"width": null, "height": null}, "is_subframe": true, "is_icon": false, "inferred_grid": null}, "theme_profile": {"description": "A single frame of a large black energy shield visual effect animation sequence.", "tags": ["fx1", "energy_shield", "large", "black", "vfx", "animation_frame"], "style": "Pixel Art", "color_descriptors": ["black", "dark purple", "white"]}, "inference_reasoning": [{"rule": "Rule 4: Multi-File Sequences", "rationale": "Filename ends with sequential numbers (frame0014.png), indicating it is part of a multi_file_animation sequence, so is_subframe is set to true."}, {"rule": "Rule 8: Visual Effects (VFX)", "rationale": "The folder name contains 'fx1_', indicating a visual effect or particle asset."}, {"rule": "Rule 16: Perspective Analysis", "rationale": "The asset is a side-view energy shield effect suitable for side-scroller games."}]}'''),

    # aura 09
    ("/Users/markoates/Assets/untiedgames/super-pixel-effects-pack-1/extracted/Super Pixel Effects Pack 1/PNG/fx1_aura_energy_large_green/frame0009.png", '''{"catalog_proposal": {"type": "multi_file_animation", "perspective": "unknown", "num_frames": 1, "cell_dimensions": {"width": null, "height": null}, "is_subframe": true, "is_icon": false, "inferred_grid": null}, "theme_profile": {"description": "A single frame of a green energy aura visual effect animation.", "tags": ["vfx", "aura", "energy", "green", "magic", "pixel art", "animation_frame"], "style": "Vibrant pixel art VFX", "color_descriptors": ["vibrant green", "soft yellow", "light cream"]}, "inference_reasoning": [{"rule": "Rule 4: Multi-File Sequences", "rationale": "The filename ends in a sequential number (frame0009.png), designating it as part of a multi-file animation sequence with is_subframe set to true."}, {"rule": "Rule 8: Visual Effects (VFX)", "rationale": "Keywords like fx1_ and aura denote a particle/VFX asset."}, {"rule": "Rule 16: Perspective Analysis", "rationale": "The asset is a generic energy aura applicable across multiple game perspectives, making its perspective unknown."}]}'''),

    # archer hit
    ("/Users/markoates/Assets/dreamir/elves-pack/extracted/Elves_Pack/Elf_Archer/Elf_Archer_Hit/Elf_Archer_Hit3.png", '''{"catalog_proposal": {"type": "multi_file_animation", "perspective": "side", "num_frames": 1, "cell_dimensions": {"width": null, "height": null}, "is_subframe": true, "is_icon": false, "inferred_grid": null}, "theme_profile": {"description": "A pixel art animation frame depicting a female elf archer in green and brown clothes taking a hit.", "tags": ["elf", "archer", "hit", "damage", "character", "animation"], "style": "16-bit retro pixel art", "color_descriptors": ["green", "brown", "blonde", "tan"]}, "inference_reasoning": [{"rule": "Rule 4: Multi-File Sequences", "rationale": "Filename ends in a sequential number (Elf_Archer_Hit3.png) indicating a multi_file_animation subframe."}, {"rule": "Rule 3: Action Signatures", "rationale": "The action verb 'Hit' indicates a character damage animation sequence."}, {"rule": "Rule 16: Perspective Analysis", "rationale": "The character sprite is rendered from a lateral 2D side-scrolling perspective."}]}''')
]

output_proposals = []
for physical_path, json_str in responses:
    rel_path = physical_path.replace("/Users/markoates/Assets/", "")
    vendor = rel_path.split("/")[0]
    pack = rel_path.split("/")[2] if "extracted" in rel_path else rel_path.split("/")[1]
    name = os.path.splitext(os.path.basename(rel_path))[0]
    
    data = json.loads(json_str)
    proposed = data["catalog_proposal"]
    
    safe_rel_path = rel_path.replace('.', '_')
    deterministic_id = f"synthetic/{safe_rel_path}"
    
    asset_dict = {
        "identifier": deterministic_id,
        "name": name,
        "asset_pack_identifier": f"{vendor}/{pack}",
        "type": proposed.get("type", "unknown"),
        "perspective": proposed.get("perspective", "unknown"),
        "is_subframe": proposed.get("is_subframe", False),
        "is_icon": proposed.get("is_icon", False),
        "visibility": "public",
        "sheet_row_number": None,
        "resource": {
            "type": proposed.get("type", "unknown"),
            "source_files": [f"/Assets/{rel_path}"],
            "cell_dimensions": proposed.get("cell_dimensions"),
            "inferred_grid": proposed.get("inferred_grid"),
            "hash": get_file_hash(physical_path)
        },
        "theme_profile": data.get("theme_profile", {}),
        "inference_reasoning": data.get("inference_reasoning", []),
        "color_profile": {
            "color_space": "unknown",
            "palette": [],
            "is_exact_palette": False,
            "palette_swappable": False
        },
        "ai_audit": {
            "pass1_model": "antigravity-flash-lite",
            "pass1_timestamp": "2026-09-13T02:56:30-04:00"
        }
    }
    output_proposals.append(asset_dict)

out_file = 'scripts/ai_subagent_proposals.json'
existing = []
if os.path.exists(out_file):
    with open(out_file, 'r', encoding='utf-8') as f:
        existing = json.load(f)

existing.extend(output_proposals)
with open(out_file + '.tmp', 'w', encoding='utf-8') as f:
    json.dump(existing, f, indent=2)
os.rename(out_file + '.tmp', out_file)
print("Successfully appended 9 MORE assets")
